CREATE COLUMN TABLE "ZZT_EXEC_JOB"
(
 "ID" NVARCHAR(64) NOT NULL,
 "TMD_JOB_BO" NVARCHAR(64),
 "DATABASE_SOURCE" NVARCHAR(100),
 "DATABASE_TARGET" NVARCHAR(100),
 "TMD_TASK_LOG_BO" NVARCHAR(64),
 "EXECUTED_DATE" TIMESTAMP,
 "EXECUTED_TIME" TIMESTAMP,
 "EXECUTED_RESULT" NVARCHAR(20),
 "RUN_STATE" NVARCHAR(20),
 "DELETE_AFTER" TIMESTAMP,
 PRIMARY KEY ("ID")
);