CREATE COLUMN TABLE "ZZT_EXEC_TASK"
(
 "ID" NVARCHAR(64) NOT NULL,
 "TMD_TASK_BO" NVARCHAR(64),
 "EXEC_JOB_BO" NVARCHAR(64),
 "TABLE_NAME" NVARCHAR(64),
 "SQL_WHERE" NVARCHAR(2000),
 "TRIGGERED_BY" NVARCHAR(64),
 "RESULT_COUNT" DECIMAL(17,17),
 "TASK_PATH" NVARCHAR(200),
 PRIMARY KEY ("ID")
);