CREATE COLUMN TABLE "ZZT_QTZ_CLOCK"
(
 "ID" NVARCHAR(64) NOT NULL,
 "START_TIME" TIMESTAMP,
 "END_TIME" TIMESTAMP,
 "CLOCK_TYPE" NVARCHAR(10),
 "CLOCK_INTERVAL" DECIMAL(17,17),
 "TMD_JOB_BO" NVARCHAR(64),
 "TRIGGER_STARTUP" NVARCHAR(1),
 PRIMARY KEY ("ID")
);