CREATE COLUMN TABLE "ZZT_QTZ_CLOCK"
(
 "ID" NVARCHAR(128) NOT NULL,
 "START_TIME" TIMESTAMP,
 "END_TIME" TIMESTAMP,
 "CLOCK_TYPE" NVARCHAR(128),
 "CLOCK_INTERVAL" DECIMAL(17,17),
 "TMD_JOB_BO" NVARCHAR(128),
 "TRIGGER_STARTUP" NVARCHAR(128),
 PRIMARY KEY ("ID")
);