//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.13 at 08:07:59 AM CST 
//


package uia.tmd.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uia.tmd.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tmd_QNAME = new QName("http://tmd.uia/model/xml", "tmd");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uia.tmd.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link TargetUpdateType }
     * 
     */
    public TargetUpdateType createTargetUpdateType() {
        return new TargetUpdateType();
    }

    /**
     * Create an instance of {@link AbstractTableType }
     * 
     */
    public AbstractTableType createAbstractTableType() {
        return new AbstractTableType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link TmdType }
     * 
     */
    public TmdType createTmdType() {
        return new TmdType();
    }

    /**
     * Create an instance of {@link DatabaseType }
     * 
     */
    public DatabaseType createDatabaseType() {
        return new DatabaseType();
    }

    /**
     * Create an instance of {@link TaskSpaceType }
     * 
     */
    public TaskSpaceType createTaskSpaceType() {
        return new TaskSpaceType();
    }

    /**
     * Create an instance of {@link TableSpaceType }
     * 
     */
    public TableSpaceType createTableSpaceType() {
        return new TableSpaceType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link JobSpaceType }
     * 
     */
    public JobSpaceType createJobSpaceType() {
        return new JobSpaceType();
    }

    /**
     * Create an instance of {@link PlanType }
     * 
     */
    public PlanType createPlanType() {
        return new PlanType();
    }

    /**
     * Create an instance of {@link ColumnMappingType }
     * 
     */
    public ColumnMappingType createColumnMappingType() {
        return new ColumnMappingType();
    }

    /**
     * Create an instance of {@link DatabaseSpaceType }
     * 
     */
    public DatabaseSpaceType createDatabaseSpaceType() {
        return new DatabaseSpaceType();
    }

    /**
     * Create an instance of {@link SourceSelectType }
     * 
     */
    public SourceSelectType createSourceSelectType() {
        return new SourceSelectType();
    }

    /**
     * Create an instance of {@link TaskType.Next }
     * 
     */
    public TaskType.Next createTaskTypeNext() {
        return new TaskType.Next();
    }

    /**
     * Create an instance of {@link TargetUpdateType.ColumnMapping }
     * 
     */
    public TargetUpdateType.ColumnMapping createTargetUpdateTypeColumnMapping() {
        return new TargetUpdateType.ColumnMapping();
    }

    /**
     * Create an instance of {@link AbstractTableType.Pk }
     * 
     */
    public AbstractTableType.Pk createAbstractTableTypePk() {
        return new AbstractTableType.Pk();
    }

    /**
     * Create an instance of {@link ItemType.Args }
     * 
     */
    public ItemType.Args createItemTypeArgs() {
        return new ItemType.Args();
    }

    /**
     * Create an instance of {@link ItemType.Filters }
     * 
     */
    public ItemType.Filters createItemTypeFilters() {
        return new ItemType.Filters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TmdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tmd.uia/model/xml", name = "tmd")
    public JAXBElement<TmdType> createTmd(TmdType value) {
        return new JAXBElement<TmdType>(_Tmd_QNAME, TmdType.class, null, value);
    }

}
