//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 07:30:00 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tmd.uia/model/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uia.tmd.model.xml;
