//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 07:30:00 下午 CST 
//


package uia.tmd.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TmdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TmdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="executorSpace" type="{http://tmd.uia/model/xml}ExecutorSpaceType"/>
 *         &lt;element name="taskSpace" type="{http://tmd.uia/model/xml}TaskSpaceType"/>
 *         &lt;element name="tableSpace" type="{http://tmd.uia/model/xml}TableSpaceType"/>
 *         &lt;element name="databaseSpace" type="{http://tmd.uia/model/xml}DatabaseSpaceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TmdType", propOrder = {
    "executorSpace",
    "taskSpace",
    "tableSpace",
    "databaseSpace"
})
public class TmdType {

    @XmlElement(required = true)
    protected ExecutorSpaceType executorSpace;
    @XmlElement(required = true)
    protected TaskSpaceType taskSpace;
    @XmlElement(required = true)
    protected TableSpaceType tableSpace;
    @XmlElement(required = true)
    protected DatabaseSpaceType databaseSpace;

    /**
     * Gets the value of the executorSpace property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutorSpaceType }
     *     
     */
    public ExecutorSpaceType getExecutorSpace() {
        return executorSpace;
    }

    /**
     * Sets the value of the executorSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutorSpaceType }
     *     
     */
    public void setExecutorSpace(ExecutorSpaceType value) {
        this.executorSpace = value;
    }

    /**
     * Gets the value of the taskSpace property.
     * 
     * @return
     *     possible object is
     *     {@link TaskSpaceType }
     *     
     */
    public TaskSpaceType getTaskSpace() {
        return taskSpace;
    }

    /**
     * Sets the value of the taskSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskSpaceType }
     *     
     */
    public void setTaskSpace(TaskSpaceType value) {
        this.taskSpace = value;
    }

    /**
     * Gets the value of the tableSpace property.
     * 
     * @return
     *     possible object is
     *     {@link TableSpaceType }
     *     
     */
    public TableSpaceType getTableSpace() {
        return tableSpace;
    }

    /**
     * Sets the value of the tableSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableSpaceType }
     *     
     */
    public void setTableSpace(TableSpaceType value) {
        this.tableSpace = value;
    }

    /**
     * Gets the value of the databaseSpace property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseSpaceType }
     *     
     */
    public DatabaseSpaceType getDatabaseSpace() {
        return databaseSpace;
    }

    /**
     * Sets the value of the databaseSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseSpaceType }
     *     
     */
    public void setDatabaseSpace(DatabaseSpaceType value) {
        this.databaseSpace = value;
    }

}
